### ISSUE TITLE
Incorrect hashes in "nodes.json" + incorrect check

### ISSUE THREAD

**Issue by tizoc** [tarides/tezos-context-hash#8]
Hello, I was integrating this into TezEdge's tests, and for some reason the "nodes" tests was failing.

I noticed that the `check_file` function, always loads "inodes.json". The fix is:

```diff
diff --git a/bin/main.ml b/bin/main.ml
index 6ed3705..61b8de3 100644
--- a/bin/main.ml
+++ b/bin/main.ml
@@ -176,7 +176,7 @@ module Nodes = struct
     generate_file config Gen.long_inode Inodes
 
   let check_file dir f =
-    let path = file dir None Inodes in
+    let path = file dir None f in
     let msg =
       match f with Nodes -> "nodes" | Inodes -> "inodes" | _ -> assert false
     in
```

After changing this, I not see that the tests fail when running the OCaml code in this repo too (which now produces the same hashes as my Rust code).

The other problem (I think) is that the generator always uses `Inter.Val.v` which I guess is for inodes, and not `Nodes.v` when producing nodes. Is my understanding here correct or is there something else I am missing?

**Comment by Ngoguey42** [comment]
`Inter.Val.v l` knows how to handle both small and large directories. Depending on the size of `l` it will choose the right hashing function.
